version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.4.1
  aws-ecr: circleci/aws-ecr@9.8.1

jobs:
  build:
    executor: aws-ecr/default
    parameters:
      dockerfile:
        type: string
      repo:
        type: string
    steps:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                profile_name: WEB_IDENTITY_PROFILE
                role_arn: ${AWS_OIDC_ROLE_ARN}
                role_session_name: circleci-happy-build
          profile_name: WEB_IDENTITY_PROFILE
          create_repo: true
          dockerfile: << parameters.dockerfile >>
          repo: << parameters.repo >>

workflows:
  version: 2
  main:
    when:
      or:
        - equal: ["<< pipeline.git.branch >>", "main"]
        - equal: ["<< pipeline.git.branch >>", "feature/ci"]
    jobs:
      - build:
          name: build-server
          dockerfile: Dockerfile.server
          repo: happy-server
      - build:
          name: build-webapp
          dockerfile: Dockerfile.webapp
          repo: happy-webapp
