resources:
  - deployment-server.yml
  - deployment-webapp.yml
  - ingress.yml
  - service-server.yml
  - service-webapp.yml
  - statefulset-postgres.yml

configMapGenerator:
  - name: happy-server-env
    envs:
      - env
